### ISSUE TITLE
Just a suggestion from experience

### ISSUE THREAD

**Issue by bozdoz** [lirantal/snyk-vs-npm-audit#2]
I was testing snyk and npm, and even jfrog, specifically to see which one would flag sweetalert2 (see all the closed issues on it being protestware if you're not famliar: https://github.com/sweetalert2/sweetalert2/issues?q=is%3Aissue+is%3Aclosed).

In my tests, snyk did identify an issue, but incorrectly assumed it was fixed on the next update (not sure if they blindly assume updates fix all issues).  Npm took 7 months to identify an issue, but as of my last test, it was the only audit solution to correctly flag the package.

Thoughts on that?

**Comment by lirantal** [comment]
Hi @bozdoz, thanks for chiming in! Super happy to get some genuine user feedback here :-)

> "assumed it was fixed on the next update"

Can you explain or give an example/reference so I can validate or reproduce what you refer to?
This is what I see if I go to the Snyk [vulnerability page](https://security.snyk.io/package/npm/sweetalert2/11.5.2) for sweetalert2:
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/316371/211624070-f71567ce-1954-4de8-86d7-135baacfb543.png">

**Comment by bozdoz** [comment]
Looks like they fixed it.  I submitted a complaint that their "How to fix" section just said to update to the latest version, though the author of the package has no intention of changing course on this topic.  At the time, it seemed as though `npm audit` gave me the best results (though 7 months after the package turned into protestware)

**Comment by bozdoz** [comment]
I did find my screenshots from November to verify some of the behaviour I saw:

<img width="801" alt="Screen Shot 2022-11-23 at 10 51 13 AM" src="https://user-images.githubusercontent.com/1410985/211692578-40bc3c79-cb5d-4d1d-b903-c43b53eabc2d.png">
With v11.6.9, snyk just said to update to the next patch version.

<img width="920" alt="Screen Shot 2022-11-23 at 12 17 24 PM" src="https://user-images.githubusercontent.com/1410985/211692657-c67bf081-eaf6-4b5a-bfd4-c7274f4684ee.png">
`npm audit` suggested downgrading to 11.4.8

**Comment by lirantal** [comment]
It is indeed possible that back then `11.6.10` did fix it and they perhaps re-introduced it.

Snyk keeps a `published date` property for when we publish a vulnerability, so you can see when was it that we found it and we don't backdate it or some other way to manipulate data:
![image](https://user-images.githubusercontent.com/316371/211908456-769776df-452b-4f88-83ca-6e997eba2d40.png)

Anyways, if I scan the `sweetalert2` package with the latest version being `11.7.0` here are the results I get:

npm audit:
```
# npm audit report

sweetalert2  >=11.4.9
sweetalert2 v11.4.9 and above contains hidden functionality - https://github.com/advisories/GHSA-qq6h-5g6j-q3cm
fix available via `npm audit fix --force`
Will install sweetalert2@11.4.8, which is a breaking change
node_modules/sweetalert2

1 low severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force
```

snyk test:
```
Tested 1 dependencies for known issues, found 1 issue, 1 vulnerable path.

Issues with no direct upgrade or patch:
  ✗ Undesired Behavior [Low Severity][https://security.snyk.io/vuln/SNYK-JS-SWEETALERT2-2774674] in sweetalert2@11.7.0
    introduced by sweetalert2@11.7.0
  No upgrade or patch available


Organization:      lirantal
Package manager:   npm
Target file:       package-lock.json
```

**Comment by lirantal** [comment]
Doesn't look like there's anything in particular to take here so I'm going to close the issue but if you have more of these type of feedback please open new issues!

**Comment by bozdoz** [comment]
Sounds good. Thanks!  Just one note on that latest scan: npm seems more correct to say the undesirable behaviour was introduced in 11.4.9; snyk for some reason identifies 11.7.0.  Anyway, thanks for your interest!

**Comment by lirantal** [comment]
> more correct to say the undesirable behaviour was introduced in 11.4.9

oh, that's interesting feedback. So what Snyk means by `introduced by sweetalert2@11.7.0` is not which version of the sweetalert2 package introduced the vulnerability initially, but rather which **installed** npm package version is introducing the said vulnerability.

You can confirm that by going to the [sweetalert2 vulnerability page](https://security.snyk.io/vuln/SNYK-JS-SWEETALERT2-2774674) and see that it indeed calls out `>= 11.4.9` as the vulnerable range.

So good opportunity to ask, which type of information would be useful for you to get? I find Snyk's detail more helpful because it tells you in your own project which npm version of the package is causing the issue, but happy to hear arguments supporting something else.

**Comment by bozdoz** [comment]
I find npm's details more **informative**, and actually probably more **useful**.  

I suppose less experienced developers may get confused at seeing a version that differs from their package.json (I know many devs don't understand what `^11.4.8` would do, for example); so in that case perhaps it's more **helpful** to them to see that they have version `11.7.0` installed.  

On the other hand, perhaps `npm audit` is more **useful** as it suggests exactly which version should be installed (because it identifies the exact version that introduced the problem), and even gives a command to auto-fix it: `npm audit fix --force`.

**Comment by lirantal** [comment]
That's helpful, thanks! will share with the team

I too wish we'd have a fix from the CLI but the team is prioritizing the GitHub integrations which offers automated fix via pull requests because truly imported git repositories provide a much superior experience. As an avid CLI user, I totally relate with you though :-)
